#### Basic Configuration for the application ####
# Configuration for the application
Test_Model: false  # Set to true to test the model

# Detection settings
confidence_threshold: 0.5
debug: true
#############################################


#### Advanced Configuration for the application ####
# Backend settings
backEnd_ip: "orderdrinks.webhop.me" # ip address of the backend server
backEnd_Port: 9000
device_id: "70cb8bfc-5b67-4115-8db6-d371e22b430b"

enable_websocket: true # Set to true to enable websocket Section
enable_RestAPI: false # Set to true to enable RestAPI Section

# Inference server settings
inference_ip: "localhost" # ip address of the inference server
inference_port: 9001 # port of the inference server

# Roboflow settings
Roboflow_api_key: "Z68TgZELV2akAABCATNm" # API key for Roboflow
Roboflow_workspace: "roboflowai" # Workspace for Roboflow
Roboflow_project: "gallon-bottle" # Project for RoboFlow
Roboflow_version: 2 # Version of the project
#############################################